name: Deploy Frontend
on: [push, pull-request]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Steps to create docker container with this image and run tests
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t platanozay/frontend -f Dockerfile.dev .
      - run: docker run -e CI=true platanozay/frontend npm run test

  deploy:
   runs-on: ubuntu-latest
    if: $ {{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up AWS CLI
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: firstfrontend
          environment_name: Firstfrontend-env
          existing_bucket_name: elasticbeanstalk-us-east-2-443370718845
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
